defaultRuntime: linuxx86_64
defaultTemplate: all
realm: deploy-service

templates:
  - Template: all

variants:
  - Variant: linuxx86_64
    runtime: linuxx86_64
branches:
  - Branch: master
    variants:
     - linuxx86_64
